---
# Python 3 with Redis 6
version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: nyu
    container_name: lab-docker
    volumes:
      - ..:/app
    command: sleep infinity
    environment:
      FLASK_APP: service:app
      FLASK_DEBUG: True
      GUNICORN_BIND: "0.0.0.0:8000"
    networks:
      - dev
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    container_name: redis
    # ports:
    #   - 6379:6379
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - redis:/data
    networks:
      - dev

volumes:
  redis:

networks:
  dev:
