name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
    - 'README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
    - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    # Required services    
    services:
      redis:
        image: redis:6-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Linting
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics
          # check for complexity. The GitHub editor is 127 chars wide
          flake8 service tests --count --max-complexity=10 --max-line-length=127 --statistics
          # Run pylint on the service
          pylint service tests --max-line-length=127

      - name: Run unit tests with PyTest
        run: pytest
        env:
          DATABASE_URI: "redis://redis:6379/0"

      - name: Upload code coverage
        uses: codecov/codecov-action@v4.1.0
